# fly.toml app configuration file generated for rexy on 2023-06-08T14:14:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rexy"
primary_region = "jnb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]
  dockerfile = "Dockerfile.test"
  ignorefile = "/path/.dockerignore"
  build-target = "test"
